language: c

script:
  - make && make run_geometry && make run_testing 
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
  

compiler: gcc

dist: xenial